import Shell from '@/components/Shell';
import PageHeader from '@/components/PageHeader';
import Link from 'next/link';

export const metadata = {
  title: 'Terms | Chatbot Forge',
  description:
    'The terms for using Chatbot Forge: what the service does, what it costs, and what each side is responsible for.',
};

/** Same caveat as /privacy: accurate about the software, not a substitute for a lawyer. */
const OPERATOR = process.env.NEXT_PUBLIC_OPERATOR_NAME || '[your company name]';
const CONTACT = process.env.NEXT_PUBLIC_SUPPORT_EMAIL || '[support@yourdomain.com]';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="card">
      <h2 className="text-sm font-semibold">{title}</h2>
      <div className="mt-2 space-y-2 text-xs leading-relaxed text-slate-600">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <Shell>
      <PageHeader
        back={{ href: '/', label: 'Home' }}
        kicker="Legal"
        title="Terms of service"
        sub={`The agreement between you and ${OPERATOR} for using Chatbot Forge.`}
      />

      <div className="max-w-2xl space-y-4">
        <Section title="What the service is">
          <p>
            Chatbot Forge lets you configure a chatbot and publish it as a link, an iframe or a widget. Answers are
            generated by a third-party AI provider that you choose, either on your own API key or on ours if you have
            credits.
          </p>
        </Section>

        <Section title="Your account">
          <p>
            Keep your password to yourself, and tell us at {CONTACT} if you think someone else has it. You can sign
            every device out at once from your account page. You must be old enough to enter a contract where you live.
          </p>
        </Section>

        <Section title="Credits and payment">
          <ul className="list-disc space-y-1 pl-5">
            <li>Credits are prepaid and are spent when a bot runs on our API keys. They do not expire.</li>
            <li>One credit covers a bounded amount of work; a larger conversation or a longer answer costs more.</li>
            <li>
              Credits are not money, cannot be transferred between accounts, and are not refundable once spent. Unspent
              credits can be refunded on request within 14 days of purchase.
            </li>
            <li>A bot running on your own API key never spends credits; you are billed directly by that provider.</li>
          </ul>
        </Section>

        <Section title="What you may not do">
          <ul className="list-disc space-y-1 pl-5">
            <li>Break the law, or the usage policies of the AI provider your bot uses.</li>
            <li>Publish a bot that impersonates a real person or organisation without their permission.</li>
            <li>Upload content to a knowledge base that you do not have the right to use.</li>
            <li>Attempt to extract our API keys, work around credit limits, or attack the service.</li>
          </ul>
          <p>Accounts doing any of the above can be suspended without notice, with unspent credits refunded.</p>
        </Section>

        <Section title="Your content">
          <p>
            Your prompts, knowledge bases and bots stay yours. You grant us only what is needed to run the service:
            storing them and sending them to the AI provider you picked. We do not use them to train models.
          </p>
          <p>
            You are responsible for what your chatbot says to your visitors. Language models get things wrong, and
            nothing here changes that. If your bot gives advice people act on, review its instructions accordingly.
          </p>
        </Section>

        <Section title="Availability and liability">
          <p>
            The service is provided as-is. We do not promise uninterrupted availability, and we depend on providers we
            do not control. To the extent the law allows, our total liability is limited to what you paid us in the
            three months before the claim.
          </p>
        </Section>

        <Section title="Ending it">
          <p>
            You can delete your account at any time from your{' '}
            <Link href="/account" className="underline underline-offset-2">account page</Link>, which erases your bots
            and their data. We may close an account that breaks these terms, or the service itself with reasonable
            notice and a refund of unspent credits.
          </p>
        </Section>

        <p className="hint">
          Replace the bracketed placeholders and have this reviewed against the law where you operate before taking
          paying customers. See also our <Link href="/privacy" className="underline underline-offset-2">privacy page</Link>.
        </p>
      </div>
    </Shell>
  );
}
